### ISSUE TITLE
Coundn't find device!

### ISSUE THREAD

**Issue by cmdrflexo** [alchitry/Alchitry-Labs#20]
Anyone get a "Couldn't find device!" error when trying to flash a program to one of the Alchitry boards (in my case a Cu)?
Sometimes I get "Couldn't find device!" and sometimes I get:

```
org.usb4java.LibUsbException: USB error 5: LibUsb.open() failed: Entity not found
at com.alchitry.labs.hardware.usb.UsbDevice.usbFindAll(UsbDevice.java:218)
at com.alchitry.labs.hardware.usb.UsbUtil.getDevice(UsbUtil.java:46)
at com.alchitry.labs.hardware.usb.UsbUtil.openFtdiDevice(UsbUtil.java:91)
at com.alchitry.labs.hardware.loaders.CuLoader.program(CuLoader.java:45)
at com.alchitry.labs.hardware.loaders.ProjectLoader.load(ProjectLoader.java:48)
at com.alchitry.labs.project.Project$8.run(Project.java:1539)
```

I have tried two different USB-C cables, both confirmed to be data cables and every single USB port and hub on my PC.

More details in forum post here: [https://forum.alchitry.com/thread-64.html](https://forum.alchitry.com/thread-64.html)

Thanks.

**Comment by alchitry** [comment]
Should be fixed in the newer versions that use D2XX
